# Generated by Django 5.1.4 on 2025-01-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_content_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'artikel', 'verbose_name_plural': 'artikels'},
        ),
    ]
