# Generated by Django 5.1.4 on 2025-01-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
